name: OAS Generator

on:
  workflow_dispatch:

env:
  TARGET_REPO: team-moeum/checkmate-frontend
  TARGET_BRANCH: main
  SOURCE_BRANCH: oas-${{ github.run_number }}-${{ github.run_attempt }}
  DATABASE_URL: ${{ secrets.DATABASE_URL }}
  DATABASE_USERNAME: ${{ secrets.DATABASE_USERNAME }}
  DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
  SERVICE_NAME: checkmate-backend-docs
  PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

jobs:
  generate-swagger:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source repository
        uses: actions/checkout@v3

      - name: Build and run application container
        run: |
          docker build \
            --build-arg DATABASE_URL=${DATABASE_URL} \
            --build-arg DATABASE_USERNAME=${DATABASE_USERNAME} \
            --build-arg DATABASE_PASSWORD=${DATABASE_PASSWORD} \
            -t swagger .

          docker run -d --network host --name ${{ env.SERVICE_NAME }} swagger

          echo "Docker container status:"
          docker ps
          docker logs ${{ env.SERVICE_NAME }}

          echo "Waiting for application to start (60 seconds)..."
          sleep 60

      - name: Download swagger JSON
        run: |
          curl -f http://localhost:8080/api-docs/json > swagger.json || exit 1

      - name: Stop container
        if: always()
        run: docker stop ${{ env.SERVICE_NAME }} || true

      - name: Checkout target repository
        uses: actions/checkout@v3
        with:
          repository: ${{ env.TARGET_REPO }}
          token: ${{ env.PERSONAL_ACCESS_TOKEN }}
          path: target-repo

      - name: Create Pull Request
        run: |
          cd target-repo
          git config --local user.email "moeum[bot]@users.noreply.github.com"
          git config --local user.name "moeum[bot]"

          git checkout -b ${{ env.SOURCE_BRANCH }}
          cp ../swagger.json ./swagger.json
          git add swagger.json
          git commit -m "Update swagger.json"
          git push origin ${{ env.SOURCE_BRANCH }}

          # 변경사항이 있는지 확인
          if ! git diff --quiet; then
            git add swagger.json
            git commit -m "Update swagger.json"
            git push origin ${{ env.SOURCE_BRANCH }}

            curl -X POST \
              -H "Authorization: token ${{ env.PERSONAL_ACCESS_TOKEN }}" \
              -H "Accept: application/vnd.github.v3+json" \
              https://api.github.com/repos/${{ env.TARGET_REPO }}/pulls \
              -d '{
                "title": "Update Swagger JSON",
                "body": "Automatically generated Swagger JSON update\n\nGenerated by workflow run #${{ github.run_number }}",
                "head": "${{ env.SOURCE_BRANCH }}",
                "base": "${{ env.TARGET_BRANCH }}"
              }'
          else
            echo "No changes in swagger.json"
          fi
